---
title: | 
  | \hfill \large{Albert Garcia}
  | \hfill \large{Jacob Gellman}
  | \hfill \large{Casey O'Hara}
  | \hfill \large{Vincent Thivierge}
author: |
  | \hfill Econ 230B
date: |
  | \hfill `r Sys.Date()`
output:
  pdf_document:
    toc: no
    number_sections: false
  html_document:
    toc: no
    number_sections: false
header-includes: 
  - \usepackage{tikz}
  - \usepackage{tikz-qtree}
  - \usepackage{pgfplots}
  - \usepackage{amsmath}
  - \usepackage{mathrsfs}
  - \usepackage{nccmath} 
---

``` {r setup, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      echo = FALSE, message = FALSE, warning = FALSE)

source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')
### loads tidyverse packages, defines helper functions

library(tidyverse)
library(latex2exp)

```

\newcommand{\EE}{\mathbb{E}}
\newcommand{\eps}{\varepsilon}
\newcommand{\LL}{\mathscr{L}}
\newcommand{\dd}{\partial}

# Problem set 4

__NOTE:__ We all worked on our problem sets individually and came to consensus on answers as a group, so we chose to collaborate on the LaTeX work and submit our final answers as a group.  Please let us know if this is a problem and we will work in smaller groups on future problem sets.

## Exercises Lecture 6

### 6.1 George’s utility function is
$$U_G(x, y) = 48x - x^2 + z_G$$
and Hazel’s utility function is 
$$U_H(x, y) = 60y - y^2 - xy + z_H$$
where $x$ is the amount of $X$ing that George does and $y$ is the amount of $Y$ing that Hazel does and where $z_G$ and $z_H$ are the amounts of bread that George and Hazel consume, respectively. When George does $x$ units of $X$ing and Hazel does $y$ units of $Y$ing, the amount of damage that George does to Hazel is equal to $xy$. George and Hazel each have fixed incomes $W_G$ and $W_H$. The set of feasible allocations consists of all vectors $(x, y, z_G, z_H) \geq 0$ such that $z_G + z_H = W_G + W_H$.

a) Find all of the Pareto optimal allocations in which George and Hazel each consume positive amounts of bread. How much $X$ is there and how much $Y$ ?
    * Pareto optimal outcomes will maximize the sum of utilities of George and Hazel:
    \begin{align*}
      \sum U = U_G + U_H &= 48x - x^2 + z_G + 60y - y^2 - xy + z_H\\
      \frac{\dd \sum U}{\dd y} &= 60 - 2y - x = 0 \\
      \Longrightarrow x &= 60 - 2y\\
      \frac{\dd \sum U}{\dd x} &= 48 - 2x - y = 0\\
      \Longrightarrow y &= 48 - 2x = 48 - 120 + 4y\\
      \Longrightarrow y &= 24; x = 12
    \end{align*}
b) Suppose that George and Hazel are not able to communicate with each other and that there is no government interference either with $X$ing or with $Y$ing. In consequence, the outcome is a (non-cooperative) Nash equilibrium in which the payoff functions are $U_G(x, y) = 48x - x^2 +z_G$ for George and $U_H(x, y) = 60y - y^2 - xy + z_H$ for Hazel. In equilibrium, how much $X$ing is there and how much $Y$?
    * Here each maximizes their own utility. George is unaffected by the externality so does not reduce his $X$ing accordingly; Hazel bears the full cost of the externality and has to adjust her $Y$ing to maximize her utility based on George's $X$ing.
    \begin{align*}
      \frac{\dd U_G}{\dd x} &= 48 - 2x = 0       & \Longrightarrow x &= 24\\
      \frac{\dd U_H}{\dd y} &= 60 - 2y - x = 0   & \Longrightarrow y &= 18
    \end{align*}
c) Suppose that there is strict legal liability, so that George has to pay Hazel for all damage that he does to her. Suppose also that transaction costs are so high that no deals are struck between George and Hazel. In equilibrium, how much $X$ is there and how much $Y$?
    * Under strict liability, now George bears the full cost of the externality caused by his $X$ing, and Hazel is fully compensated.  Now, George will adjust his $X$ing to account for the additional cost of the externality to himself, while Hazel will simply do her thing without a care.
$$U_G = 48x - x^2 -xy + z_G; \hspace{6pt} U_H = 60y - y^2 + z_H$$
    \begin{align*}
      \frac{\dd U_H}{\dd y} &= 60 - 2y = 0     & \Longrightarrow y = 30\\
      \frac{\dd U_G}{\dd x} &= 48 - 2x - y = 0 & \Longrightarrow x = \frac{1}{2}(48 - 30) = 9
    \end{align*}

### 6.2 Suppose that George and Hazel of the previous problem are still unable to communicate or make deals between them.
The government decides to impose a tax of $tx$ on George where $x$ is the amount of activity $X$ that he does. The government seeks a tax rate that will induce George and Hazel to perform Pareto optimal amounts of activities $X$ and $Y$.

a) If the government gives all of the tax revenue to Isolde, whom you haven’t yet met, what tax rate $t$ must it use to induce George and Hazel to perform Pareto optimal amounts of activities $X$ and $Y$.
    * To reach the Pareto optimal amount of $X$ and $Y$ (i.e. (12, 24), from 6.1a), tax George but Hazel gets no benefit (i.e. taxing the harm but not compensating the victim):
    $$U_G = 48x - x^2 + z_G - tx; \hspace{6pt} U_H = 60y - y^2 + z_H$$
    \begin{align*}
      \frac{\dd U_G}{\dd x} &= 48 - 2x - t = 0\\
      \Longrightarrow t &= 48 - 2\times 12 = 24
    \end{align*}
    * The tax on George to reach Pareto optimality is $t = 24$.
b) If the government gives all of the tax revenue to Hazel, what tax rate $t$ must it use to induce George and Hazel to perform Pareto optimal amounts of activities $X$ and $Y$.
    * In this case, now the tax on George is distributed to Hazel.
    $$U_G = 48x - x^2 + z_G - tx; \hspace{6pt} U_H = 60y - y^2 + z_H + tx$$
    \begin{align*}
      \frac{\dd U_G}{\dd x} &= 48 - 2x - t = 0\\
      \Longrightarrow t &= 48 - 2\times 12 = 24\\
      \frac{\dd U_H}{\dd y} &= 60 - 2y - x = 0\\
      \Rightarrow &\text{ $t$ is unaffected by Hazel's actions}
    \end{align*}
    * Since the tax is on $x$ but Hazel only controls $y$, the revenue to her does not affect the amount of $X$ing that George does.  Hazel may want _more_ $X$ing now, since she earns utility from the revenue, but she has no say in the matter; she can neither communicate nor make a deal with George.  Therefore, compensating the victim does not change the tax needed to bring the system into Pareto optimality (i.e. $t = 24$).
c) If the government gives half of the tax revenue to Hazel and half to George, what tax rate $t$ must it use to induce George and Hazel to perform Pareto optimal amounts of activities $X$ and $Y$.
    * In this case, George actually gets a little kickback from his taxes.  This reduces the effective impact of the tax on his decision about $X$ing, so the tax must be higher to bring the situation into Pareto optimality.
      $$U_G = 48x - x^2 + z_G - tx + \frac{1}{2}tx; \hspace{6pt} U_H = 60y - y^2 + z_H + \frac{1}{2}tx$$
      \begin{align*}
      \frac{\dd U_G}{\dd x} &= 48 - 2x - .5t = 0\\
      \Longrightarrow .5t &= 48 - 2\times 12 \Rightarrow t = 48\\
      \frac{\dd U_H}{\dd y} &= 60 - 2y - x = 0\\
      \Rightarrow &\text{ $t$ is still unaffected by Hazel's actions}
    \end{align*}
    * As in 6.2b, the compensation (partial, in this case) to Hazel does not change the necessary tax rate.  But the partial reimbursement to George _does_ change the necessary tax rate.  When George bears a tax of $t = 24$ (from 6.2a), he abates his $X$ing to the Pareto optimal level; by reimbursing him half the tax, we must now double the tax rate so that he again has to pay a total of $t_{effective} = 24$ to change his behavior. 

### 6.3 Suppose that the government introduces a market for the right to perform activity X. 
In this market, demand and supply curves are defined as follows: At any price $p$, $D(p)$ is the amount of $X$ing that George would choose to do if each unit of $X$ cost him $p$. At price $p$, $S(p)$ is the amount of $X$ing that Hazel would want George to do if she is paid $p$ for each unit of $X$ing that George does. Find the equilibrium price at which $D(p) = S(p)$ and the amount of $X$ing and of $Y$ing that would take place when the price of $X$ing is set at the equilibrium level.

* In a competitive market, supply and demand of $X$ must be equal at equilibrium.  According to the way Schweizer sets up the problem (assuming $X$ is desirable, not problematic as in this case) George's utility will be increased by the price of supplying $X$ and Hazel's utility would be decreased by the same amount.  If $p$ ends up being negative, then George will have to pay out of his pocket to continue to do $X$, limited by his personal wealth $z_G$.
$$U_G = 48x - x^2 + z_G + px; \hspace{6pt} U_H = 60y - y^2 + z_H - px$$
\begin{align*}
  S(p) &= \text{argmax}_{x,y} (60x - y^2 - px)\\
  \frac{\dd U_H}{\dd x} &= - y - p = 0        &\Rightarrow p = - y\\
  \frac{\dd U_H}{\dd y} &= 60 - 2y - x  = 0   &\Rightarrow x = 60 - 2y\\
  D(p) &= \text{argmax}_x (48x - x^2 + px)\\
  \frac{\dd U_G}{\dd x} &= 48 - 2x + p = 0\\
    &= 48 - 2(60 - 2y) - y = 0                &\Rightarrow y = 24\\
  \Rightarrow x &= 12\\
  \Rightarrow p &= -24
\end{align*} 
* A price of $p = -24$ means George has to pay 24 slices of bread for each unit of $X$ he performs; Hazel receives this much for each unit of George's $X$ing.  
* Note this is subject to a budget constraint: $px \leq z_G$, otherwise George can't afford as much $X$ as he would prefer.

### 6.4 Suppose that George and Hazel of the previous problems are able to communicate cheaply and easily. 
Whenever there are possible gains from a deal between them, they will make a deal. The outcome of the deal always turns out to be the Nash bargaining solution (sometimes called the “cooperative” Nash solution). In any situation, they recognize a “threat point”, which is the distribution of utility $(\bar U_G, \bar U_H)$ that they would achieve if they make no deal. The result of bargaining is that they find the point on the utility possibility frontier that maximizes the product $(U_G - \bar U_G)(U_H - \bar U_H)$ over all possible utility distributions in their utility possibility set. Prove that in doing so, Hazel and George will choose the point on the utility possibility frontier such that $U_G - \bar U_G = U_H - \bar U_H$. Would this be true regardless of the shape of the utility possibility frontier? Explain. 
  
* The bargaining point solves  
  \begin{align*}  
    \max\limits_{X,Y} (U_G-\bar{U}_G)(U_H-\bar{U}_H)
  \end{align*}
* Taking FOCs:  
  \begin{align*}
    &\frac{\dd U}{\dd X} = \frac{\dd U_G}{\dd X}U_H + \frac{\dd U_H}{\dd X}U_G -  
        \frac{\dd U_G}{\dd X}\bar{U}_H - \frac{\dd U_H}{\dd X}\bar{U}_G=0  \\
    &\frac{\dd U}{\dd Y} = \frac{\dd U_G}{\dd Y}U_H + 
        \frac{\dd U_H}{\dd Y}U_G -  
        \frac{\dd U_G}{\dd Y}\bar{U}_H - 
        \frac{\dd U_H}{\dd Y}\bar{U}_G=0  \\
    \Rightarrow &\frac{\dd U}{\dd X} = \frac{\dd U}{\dd Y}\\
    \Rightarrow &\frac{\dd U_G}{\dd X}U_H + \frac{\dd U_H}{\dd X}U_G -  
        \frac{\dd U_G}{\dd X}\bar{U}_H - \frac{\dd U_H}{\dd X}\bar{U}_G = 
        \frac{\dd U_G}{\dd Y}U_H + \frac{\dd U_H}{\dd Y}U_G - 
        \frac{\dd U_G}{\dd Y}\bar{U}_H - \frac{\dd U_H}{\dd Y}\bar{U}_G  \\
    \Rightarrow & (\frac{\dd U_H}{\dd X} - 
        \frac{\dd U_H}{\dd Y})(U_G-\bar{U}_G) = 
        (\frac{\dd U_G}{\dd Y} - \frac{\dd U_G}{\dd X})(U_H-\bar{U}_H)  \\
  \end{align*}
* Recall from the Samuelson condition for $X$:  
  \begin{align*}
  \frac{\dd U_G / \dd X}{\dd U_G / \dd Z_G} + 
      \frac{\dd U_H / \dd X}{\dd U_H / \dd Z_H} &= MSC_X & \\
  \Rightarrow \frac{\dd U_G}{\dd X} + 
      \frac{\dd U_H}{\dd X} &= 0 
      & \text{ (since utility is quasilinear, and $MSC_X = 0$)}\\
  \Rightarrow \frac{\dd U_G}{\dd X} &= - \frac{\dd U_H}{\dd X} & \\
  \end{align*}
* The Samuelson condition for $Y$:  
  \begin{align*}
    \frac{\dd U_G / \dd Y}{\dd U_G / \dd Z_G} + 
        \frac{\dd U_H / \dd Y}{\dd U_H / \dd Z_H} &= MSC_Y & \\
    \Rightarrow \frac{\dd U_G}{\dd Y} + 
        \frac{\dd U_H}{\dd Y} &= 0 
        & \text{ (since utility is quasilinear, and $MSC_Y = 0$)}\\
    \Rightarrow \frac{\dd U_G}{\dd Y} &= - \frac{\dd U_H}{\dd Y} & \\
  \end{align*}
* Subbing in to the condition derived from the FOCs:  
  \begin{align*}
    & (\frac{\dd U_H}{\dd X} - 
        \frac{\dd U_H}{\dd Y})(U_G-\bar{U}_G) 
        = (\frac{\dd U_G}{\dd Y} - 
        \frac{\dd U_G}{\dd X})(U_H-\bar{U}_H)  \\
    \Rightarrow & (\frac{\dd U_H}{\dd X} - 
        \frac{\dd U_H}{\dd Y})(U_G-\bar{U}_G) 
        = (-\frac{\dd U_H}{\dd Y} - 
        (-\frac{\dd U_H}{\dd X}))(U_H-\bar{U}_H)  \\
    \Rightarrow & (U_G-\bar{U}_G) = (U_H-\bar{U}_H)  \\
  \end{align*}
* This result depended on quasilinear utility forms, so if the private good affected the Samuelson condition then we might not achieve the same result.  

### 6.5 Suppose that George and Hazel from the previous problems have no transactions costs and always bargain to the Nash bargaining solution.

a) Assuming that there is no government interference, so that the threat point is the noncooperative Nash equilibrium, find the predicted amount of $X$ing and of $Y$ing and the predicted distribution of income and of utility between George and Hazel.

* The non-cooperative NE is given by $(\bar{U}_G,\bar{U}_H)$. From 6.1 (b), we found that the non-cooperative NE gave $\bar{X}=24$, $\bar{Y}=18$.  
  \begin{align*}
    \Rightarrow \bar{U}_G &= 48(24) - 24^2 + Z_G\\
    &= 576 + W_G\\
    \wedge \ \bar{U}_H &= 60(18) - 18^2 - (18)(24) + Z_H\\
    &= 324 + W_H
  \end{align*}

* With zero transactions costs, by the Coase theorem, George and Hazel achieve the Pareto optimal $X$ and $Y$, which we earlier found to be $X^*=12$, $Y*=24$. Following the relationship of problem 6.4,  
  \begin{align*}
    U_G - \bar{U}_G &= U_H - \bar{U}_H\\
    \Rightarrow 48(12) - 12^2 + Z_G - 576 - W_G &= 
      60(24) - 24^2 - 12(24) + Z_H - 324 - W_H\\
    \Rightarrow Z_G - W_G - 144 &= Z_H - W_H + 252\\
    \Rightarrow Z_G - W_G &= Z_H-W_H + 396
  \end{align*}

* Note that $Z_G=W_G+W_H-Z_H$.  
  \begin{align*}
    \Rightarrow W_G+W_H-W_G-Z_H &= -W_H+396+Z_H\\
    \Rightarrow 2W_H - 396 &= 2Z_H\\
    \Rightarrow \boxed{Z_H = W_H-198} & \wedge \boxed{Z_G = W_G + 198} \\
  \end{align*}

* $U_G$ from bargaining is given by $48(12)-12^2+W_G+198$. $U_H$ from bargaining is 
  given by $60(24)-24^2-12(24)+W_H-198$.  
  \begin{align*}
    \Rightarrow \boxed{U_{G,bargain}=W_G+630} \wedge \boxed{U_{H,bargain} = W_H+378}
  \end{align*}

b) Assuming that the government imposes strict liability and that the threat point is the noncooperative Nash equilibrium that would obtain under these rules, find the predicted amount of $X$ing and of $Y$ing and the predicted distribution of income and of utility between George and Hazel.

* From 6.1 (C), the non-cooperative NE is $\bar{X}=9$ $\wedge$ $\bar{Y}=30$.  
  \begin{align*}
    \Rightarrow \bar{U}_G &= 48(9)-9^2-9(30)+Z_G\\
    &= 81 + Z_G\\
    &= 81 + W_G\\
    \wedge \ \bar{U}_H &= 60(30)-30^2+Z_H\\
    &=900 + Z_H\\
    &=900 + W_H
  \end{align*}

* Again by the Coase theorem, George and Hazel achieve the Pareto optimal $X$ and $Y$,
  $X^*=12$ $\wedge$ $Y^*=24$. From 6.4,
  \begin{align*}
    U_G-\bar{U}_G &= U_H-\bar{U}_H\\
    \Rightarrow 48(12) - 12^2 -12(24) + Z_G - 81 - W_G &= 
      60(24)-24^2 +Z_H - 900 - W_H\\
    \Rightarrow 99 + Z_G - W_G &= Z_H - W_H
  \end{align*}

* Note that $Z_G=W_G+W_H-Z_H$.
  \begin{align*}
    \Rightarrow 99 + W_G + W_H - Z_H - W_G &= Z_H - W_H\\
    \Rightarrow 2W_H + 99 &= 2Z_H\\
    \Rightarrow \boxed{Z_H = W_H + \frac{99}{2}} & \wedge 
      \boxed{Z_G = W_G - \frac{99}{2}}
  \end{align*}

* $U_G$ from bargaining is $48(12)-12^2-12(24)+W_G-\frac{99}{2}$. 
  $U_H$ from bargaining is $60(24)-24^2+W_H+\frac{99}{2}$.
  \begin{align*}
    \Rightarrow \boxed{U_{G,bargain}=W_G+\frac{189}{2}} \wedge 
      \boxed{U_{H,bargain} = W_H+\frac{1827}{2}}
  \end{align*}

### 6.6 Suppose that George and Hazel from the previous problems have no transactions costs and always bargain to the Nash bargaining solution. The government imposes the tax rate $t$ that induced George to perform a Pareto optimal amount of activity $X$ when George and Hazel were unable to bargain and the money was given to Isolde.

a) If the government gives the tax revenue to Isolde, what levels of activities $X$ and $Y$ will George and Hazel choose?
    * If George is taxed at the rate from question 6.3, his budget constraint, and therefore, the joint feasibility constraint, is altered. The corresponding Lagrangian is as follows:
      \begin{align*}
        \LL       &= \lambda_1[48x - x^2 + z_G] + \lambda_2[60y - y^2 - xy + z_H] + 
            \mu[w_G + w_H - z_G - z_H - tx]\\
        \LL_x     &= \lambda_1[48 - 2x] - \lambda_2y = t\mu\\
        \LL_y     &= \lambda_2[60 - 2y - x] = 0\\
        \LL_{z_G} &= \lambda_1 = \mu\\
        \LL_{z_H} &= \lambda_2 = \mu
      \end{align*}
    * Accounting for the fact that $t = 24$ yields the following two equations:
      \begin{align*}
        48 - 2x &= 24 + y\\
        x &= 60 - 2y
      \end{align*}
    * Solving these gives $x = -4$, which is not feasible. Thus, George is put at a corner and $x = 0$. Then, $y = 30$. 
b) If the government splits the tax revenue between George and Hazel, what levels of activities $X$ and $Y$ will George and Hazel choose?
    * Similar to above, the feasibility constraint is altered. We now have the constraint:
      \begin{align*}
        z_G + \frac{1}{2} tx + z_H + \frac{1}{2} tx - tx &\leq w_G + w_H\\
        \Leftrightarrow z_G + z_H &\leq w_G + w_H
      \end{align*}
    * We then have the same budget constraint as the initial case. We know the Nash bargaining solution attains the efficient outcome, and thus, $x = 12$, $y = 24$ as found before. 

### 6.7 Hazel and George have one and only chance to make a deal. 
The chance works like this. Hazel offers George an all-or-nothing proposition. If George reduces his $X$ing to a level $x^*$, Hazel will give him a lump sum payment of $z^*$ dollars. If George rejects this deal, then the outcome will revert to the noncooperative Nash equilibrium in which there is no government interference. After George has either accepted or rejected the deal that he is offered, Hazel can decide on the amount of $Y$ing that she will do. Hazel knows George’s utility function. Assuming that George will accept any deal that is as good or better for him than the Nash equilibrium outcome, what combination of $x^*$ and $z^*$ should Hazel make in order to maximize her utility?

* Recall in Nash equilibrium that $x=24$, $y=18$. This gives:
  \begin{align*}
    U_G = 576 + z_G\\
    U_H = 324 + z_H
  \end{align*}
* If Hazel is to make an offer to George, she knows he will accept if
  \begin{align*}
    U(x^*) + z^* \geq 576 + z_G\\
    \Leftrightarrow 48x^* - x^{*2} + z^* \geq 576
  \end{align*}
* Then Hazel maximizes 
$$60y - y^2 - x^*y + z_H - z^* \hspace{5mm} \text{s.t.} \hspace{5mm} 48x^* - x^{*2} + z^* \geq 576$$
* First order conditions reveal:
  \begin{align*}
    60 - 2y - x &= 0\\
    -y + 48 - 2x &= 0
  \end{align*}
* This yields $x^* = 12$, $z^* = 576 + 144 - 48(12) = 144$.

### 6.8 This problem is like the previous one except for one thing. Hazel does not know George’s utility function. 
Hazel knows that George’s utility function is of the functional form: $U_G(x, z_G) = Ax - x^2 + z_G$, but all she knows about $A$ is that with probability 1/2, $A = 36$ and with probability 1/2, $A = 60$.

a) Hazel offers to give George a lump sum payment of of $z^*$ dollars if he reduces his amount of $X$ing to $x^*$. What choice of $z^*$ and $x^*$ would maximize Hazel’s expected utility.

> _Hint: There are only two interesting strategies for Hazel. She might choose $x^*$ and $z^*$ so that George is sure to accept her offer, whether $A = 60$ or $A = 36$. Alternatively, she might choose $x^*$ and $z^*$ so that George will accept her offer if and only if $A = 36$. For each of these two strategies there is a best choice of $x^*$ and $z^*$. Find these two solutions. Then compare Hazel’s utility under each solution._

*  For the noncooperative Nash equilibria $y=18$ and: 

\begin{align*}
  x = \begin{cases} 
        18 & \text{if $A=36$}    \\
          30 & \text{if $A=60$}      
           \end{cases}
\end{align*}

* If Hazel is to make an offer to George, he will accept if: 

\begin{align*}
  x = \begin{cases} 
        U(x^*)+ z^* \geq 324 + z_g & \text{if $A=36$}    \\
        U(x^*)+ z^* \geq 900 + z_g  & \text{if $A=60$}      
           \end{cases}
\end{align*}

  \[ \Leftrightarrow x = \begin{cases} 
        36x^* - (x^*)^2 + z^*\geq 324 & \text{if $A=36$}    \\
        60x^* - (x^*)^2 + z^* \geq 900  & \text{if $A=60$}      
           \end{cases}
    \]

Strategy 1 by Hazel: Making sure George accepts independent of his type, hence pick $x^*$ when $A=60$ and Hazel maximizes: 

$$60y - y^2 - x^*y + z_H - z^* \hspace{5mm} \text{s.t.} \hspace{5mm} 60x^* - (x^*)^2 \geq 900$$

* FOCs: 
\begin{align*}
 & 60 - 2y - x =0\\
 & y + 60 -2x = 0\\
\end{align*} 

* This yields $x^* = 20$, $z^* =  100$. George accepts for both of his types. 

Strategy 2 by Hazel: Only make sure George accepts if $A=36$

$$60y - y^2 - x^*y + z_H - z^* \hspace{5mm} \text{s.t.} \hspace{5mm} 36x^* - (x^*)^2 \geq 324$$

* FOCs: 
\begin{align*}
 & 60 - 2y - x =0\\
 & y + 36 -2x = 0\\
\end{align*} 

* This yields $x^* = 4$, $z^* =  196$. George accepts only if $A=36$.

* Now to compare the utilities of each strategy: 

\begin{align*}
& U^H(20,100) = 300 + W_H \\
& E\[U^H(4,196)\] = 324 + W_H \\
\end{align*} 

Since $U^H(20,100) <E\[U^H(4,196)\]$, she would pick the second strategy. 

b) Show that for any offer that Hazel makes, there is a probability of at least 1/2 that the amount of $X$ selected by George is not Pareto optimal.

From (a), we found that $U^H(20,100) <E\[U^H(4,196)\]$, Hazel will pick strategy 2. By definition, there is a 1/2 chance that if George ends up being a $A=60$ type, then he will reject the offer and it will not be pareto optimal. 

## Exercises Lecture 7

### 3.1 Residents of Carburetor, Ohio (pop. $n$), have utility functions
$$U_i(D_i, M_i, C) = A_i D_i - \frac{1}{2}D_i^2 - D_i \frac{D}{H} + M_i$$
where for each $i$, $D_i$ is driving by $i$, $D = \sum_{j=1}^n D_j$, $M_i$ is money expenditure by $i$ on goods, $H$ is total highway expenditures in Carburetor and where $A_i > 1$ is a parameter for each $i$. Gasoline is available for free in Carburetor, and it costs nothing to maintain cars. The only goods that money can buy in Carburetor are Big Macs and highway improvements. The initial endowment of income is $W_i$ for each $i$. The price of Big Macs is \$1.

1. Since preferences are quasilinear, the Pareto optimal amount of driving for each $i$ and the Pareto optimal total highway expenditures must be independent of income distribution (except for the case of Pareto optimal allocations where some consumers consume no Big Macs). Find these Pareto optimal quantities.
    * Samuelson condition for efficient amount of highway expenditure, $H$
      \begin{align*}
         C_{H}(C,D) \sum^{n}_{j=1}\left(\frac{U^i_C(M_j, D_j, C)}{U^i_M(M_j, D_j, C}\right) &= p_H \\
        \frac{D}{H^2} \sum^{n}_{j=1} D_i &= p_H \\
        H &= \frac{\sqrt{p_H}}{D}
      \end{align*} 
    * Samuelson condition for efficient amount of driving, $D$
      \begin{align*}
        & \frac{U^i_D(M_j, D_j, C)}{U^i_M(M_j, D_j, C)} +  C_{D}(D,H) \sum^{n}_{j=1}\left(\frac{U^i_C(M_j, D_j, C)}{U^i_M(M_j, D_j, C)}\right) = 0 \\
        & A_i - D_i - \frac{D}{H} - \frac{1}{H} \sum^{n}_{j=1} D_i = 0 \\
        & A_i - D_i - 2\frac{D}{H} = 0 \\
        & D_i = A_i - 2\frac{D}{H} \\
        & \sum^{n}_{j=1}D_i = \sum^{n}_{j=1}\left(A_i - 2\frac{D}{H} \right)\\
        &  D =  \sum^{n}_{j=1}A_i - 2n\frac{D}{H} 
      \end{align*} 
    * Combining both initial solution with endogeneous terms 
      \begin{align*}
        & D^* = \sum^{n}_{j=1}A_i - 2n\sqrt{p_H} \\
        & H^* = \frac{1}{\sqrt{p_H}} \sum^{n}_{j=1}A_i - 2n
      \end{align*} 
2. If no tolls are charged, find the Nash equilibrium amount of driving by each resident of Carburetor.
      \begin{align*}
        & \max \limits_{D_i, M_i} U_i(D_i, M_i, C) \hspace{10pt} \text{s.t.} \hspace{10pt} M_i \leq W_i \\
        & \max \limits_{D_i} A_i D_i - \frac{1}{2}D_i^2 - D_i \frac{D}{H} + W_i 
      \end{align*} 
FOC: 
      \begin{align*}
        & A_i - D_i - \frac{D_i}{H} - \frac{D}{H} = 0 \\
        & D_i \left(\frac{H + 1}{H} \right)  = A_i - \frac{D}{H}  \\
        & D_i = \frac{H}{H + 1} A_i -  \frac{D}{H + 1} \\
        & D = \frac{H}{H + 1} \sum^{n}_{j=1}A_i -  \frac{nD}{H + 1} \\
        & D^* = \frac{1}{1 + \frac{n}{H + 1}}\frac{H}{H + 1} \sum^{n}_{j=1}A_i  \\
        & D^* = \frac{H}{H + n + 1} \sum^{n}_{j=1}A_i  \\
        \implies &D_i^* = \frac{1}{H + 1}\left( H A_i - \frac{H}{H + n + 1} \sum^{n}_{j=1}A_i \right)
      \end{align*} 
3. Suppose that each resident of Carburetor is charged a uniform toll according to the rule suggested in the text of this lecture. What will this toll be? How much driving will each $i$ do?

\begin{align*}
  & T = -p_H \left( \frac{C_D(D,H)}{C_H(D,H)} \right) \\
  & T = p_H \frac{H}{D} 
\end{align*}
Now let: 
\begin{align*}
  & MRS^D_i = p_H \frac{H}{D} \\
  & A_i - D_i - \frac{D_i}{H} - \frac{D}{H}= p_H \frac{H}{D}  \\
  & D_i \left(\frac{H+1}{H}\right) = A_i -\frac{D}{H} - p_H \frac{H}{D} \\
  & D_i^* = \frac{H+1}{H}\left(H A_i -D^* - \frac{p_H H^2}{D^*} \right) \\
  & \text{...solving for $D^*$ was too cumbersome, must have made some algebra mistakes.}
\end{align*} 
