---
title: | 
  | \hfill \Large{Casey O'Hara}
author: |
  | \hfill Econ 230B
date: |
  | \hfill `r Sys.Date()`
output:
  pdf_document:
    toc: no
    number_sections: false
  html_document:
    toc: no
    number_sections: false
header-includes: 
  - \usepackage{tikz}
  - \usepackage{tikz-qtree}
  - \usepackage{pgfplots}
  - \usepackage{amsmath}
  - \usepackage{mathrsfs}
---

``` {r setup, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      echo = FALSE, message = FALSE, warning = FALSE)

source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')
### loads tidyverse packages, defines helper functions

library(latex2exp)

```

\newcommand{\EE}{\mathbb{E}}
\newcommand{\eps}{\varepsilon}
\newcommand{\LL}{\mathscr{L}}

<!-- This is a template for homework assignments to be written in LaTeX formatting -->

# Exercises Lecture 7

### 3.1 Residents of Carburetor, Ohio (pop. $n$), have utility functions
$$U_i(D_i, M_i, C) = A_i D_i - \frac{1}{2}D_i^2 - D_i \frac{D}{H} + M_i$$
where for each $i$, $D_i$ is driving by $i$, $D = \sum_{j=1}^n D_j$, $M_i$ is money expenditure by $i$ on goods, $H$ is total highway expenditures in Carburetor and where $A_i > 1$ is a parameter for each $i$. Gasoline is available for free in Carburetor, and it costs nothing to maintain cars. The only goods that money can buy in Carburetor are Big Macs and highway improvements. The initial endowment of income is $W_i$ for each $i$. The price of Big Macs is \$1.

1. Since preferences are quasilinear, the Pareto optimal amount of driving for each $i$ and the Pareto optimal total highway expenditures must be independent of income distribution (except for the case of Pareto optimal allocations where some consumers consume no Big Macs). Find these Pareto optimal quantities.
2. If no tolls are charged, find the Nash equilibrium amount of driving by each resident of Carburetor.
3. Suppose that each resident of Carburetor is charged a uniform toll according to the rule suggested in the text of this lecture. What will this toll be? How much driving will each $i$ do?