
## Reflections on Preference Revelation readings

Readings referenced in this reflection:

* Chen, Y., & Plott, C. R. (1996). The Groves-Ledyard mechanism: An experimental study of institutional design. _Journal of Public Economics_, 59(3), 335–364. https://doi.org/10.1016/0047-2727(95)01506-X
* Groves, T., & Ledyard, J. (1977). Optimal Allocation of Public Goods: A Solution to the “Free Rider” Problem. _Econometrica_, 45(4), 783. https://doi.org/10.2307/1912672
* Jackson, M. O. (2014). Mechanism Theory. _SSRN Electronic Journal_. https://doi.org/10.2139/ssrn.2542983
* Ledyard, J. (2009). Voting and Efficient Public Good Mechanisms. (D. A. Wittman & B. R. Weingast, Eds.) (Vol. 1). Oxford University Press. https://doi.org/10.1093/oxfordhb/9780199548477.003.0027

Groves-Ledyard:

* Pareto optimality; separate message from tax paid by i, so removes incentive to be dishonest.
* Problems with Naive gov't (free rider problem) and Lindahl government (requires truth but incentivizes untruthfulness)
* Proposes Optimal Gov't:
    * $y(m) \equiv \sum_i m^i$
    * $$C^i(m, s) = a^i q \cdot \sum_h m^h + \frac{\gamma}{2} \left[ \frac{I - 1}{I}[m^i - \mu m^{\sim i}]^2 - \sigma(m^{\sim i})^2 \right]$$
    * (see eqns 4.3 and 4.4 for details)
Decouples message for i, m_i, from the tax paid by i, so effectively removes incentive to be untruthful.
* Interesting commentary on literature - particularly on differentiating from VCG, 
    * "The third body of related literature consists of papers developing and applying a class of incentive mechanisms for inducing agents to communicate truthfully to a central agent and thereby enabling him to take optimal or efficient decisions. The allocation and tax rules presented in Section 3, equations (3.1), are based on this class of mechanisms."
    * "Our model and mechanism is to be distinguished from t a full general equilibrium model in which income effects not freely transferrable), and (2) by guaranteeing that th always balanced, as is required by Walras' Law for Par 4.1). In the papers mentioned above, the government budget, except in very special cases. Because of this diffi mechanism as impractical although he did not recognize that the problem could be reduced in severity"

Chen-Plott:

* GL is essentially a th


Pivotal mechanism: VCG?

