---
title: | 
  | \hfill \large{Albert Garcia}
  | \hfill \large{Jacob Gellman}
  | \hfill \large{Casey O'Hara}
  | \hfill \large{Vincent Thivierge}
author: |
  | \hfill Econ 230B
date: |
  | \hfill `r Sys.Date()`
output:
  pdf_document:
    toc: no
    number_sections: false
  html_document:
    toc: no
    number_sections: false
header-includes: 
  - \usepackage{tikz}
  - \usepackage{tikz-qtree}
  - \usepackage{pgfplots}
  - \usepackage{amsmath}
  - \usepackage{mathrsfs}
  - \usepackage{nccmath} 
---

``` {r setup, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      echo = FALSE, message = FALSE, warning = FALSE)

source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')
### loads tidyverse packages, defines helper functions

library(tidyverse)
library(latex2exp)

```

\newcommand{\EE}{\mathbb{E}}
\newcommand{\eps}{\varepsilon}
\newcommand{\LL}{\mathscr{L}}
\newcommand{\dd}{\partial}

# Problem set 5

## Exercises lecture 8

### 8.1 Every morning, 6,000 commuters must travel from East Potato to West Potato. There are two ways to make the trip. 
One way is to drive straight across town, through the heart of Middle Potato. The other way is to take the Beltline Freeway that circles the Potatoes. The Beltline Freeway is entirely uncongested, but the drive is roundabout and it takes 45 minutes to get from East Potato to West Potato by this means. The road through Middle Potato is much shorter and if it were uncongested it would take only 20 minutes to make the trip. Given the current size of the road through Middle Potato, if the number of commuters using the road is $N_1$, the time it takes to drive from East Potato to West Potato by this road is $20 + N_1/100$.

a) With the road at its current size and with no tolls, how many commuters will use the road through Middle Potato? What will be the total number of minutes per morning spent by all commuters going from East Potato to West Potato?

    * Commuters will decide which road to take based on their utility, which without additional information, we assume is directly related to how long it takes to get to West Potato, or WePo. Equilibrium will occur when the marginal commuter's WePo commute time (i.e. disutility) on the Beltway, or BF, is the same as the time it takes to drive through Middle Potato, or MoPo.
\begin{align*}
  U_{i,BF} &= U_{i,MoPo} &\text{(at equilibrium)}\\
  -45 &= -(20 + \frac{x}{100})\\
  \Rightarrow x &= (45 - 20) * 100  = 2500 
\end{align*}
    * Once 2500 drivers have chosen the MoPo route, the two commute times will be equal and commuters will be indifferent between the two routes; if any more were to consider this route, then it would take longer and therefore they would opt to take the BF route.
    * All drivers will now take 45 minutes to commute to WePo, so $45 * 6000 = 270,000$ total driver-minutes each morning.

b) Suppose that a social planner controlled access to the road through Middle Potato and chose the number of commuters who were allowed to use the Middle Potato road in such a way as to minimize the sum of the number of minutes spent by commuters traveling from East Potato to West Potato. How many commuters would the social planner permit to use the Middle Potato road each morning? How long would it then take the commuters who used this road to make their morning commute?

    * The social planner will minimize the total commuting time (i.e. maximize utility), dividing commuters into $x$ taking the MoPo route and $(6000 - x)$ taking the BF route:
\begin{align*}
  U_{tot} = \sum U_i &= \sum_{i-1}^{x} -(20 + \frac{x}{100}) + \sum_{i=x+1}^{6000} -45\\
    &= -20x - \frac{x^2}{100} - 45 (6000 - x)\\
  \frac{\dd U_{tot}}{\dd x} &= 25 - \frac{x}{50} = 0 &\text{(first order cond'ns)}\\
  \Rightarrow x &= 1250
\end{align*}
    * The commute for drivers taking the BF route will still take 45 minutes; the commute for drivers assigned to take the MoPo will take only $20 + x/100 = 32.5$ minutes.
    * Total commute time for the entire EPo community is $45 (6000 - x) + 32.5x = 254,375$ minutes.

c) Suppose that commuters value time saved from commuting at $\$w$ per minute. Suppose that the government charges a toll for driving on the road through Middle Potato and divides the revenue from the toll equally among all 6,000 commuters. If the government's objective is to minimize the total amount of time that people spend commuting, how high should it set the toll? How much revenue will it collect? With this policy, how much better off (evaluated in dollars) is each
commuter than they were in the equilibrium with no tolls?

    * The toll should be set such that the marginal commuter is indifferent between the BF route and MoPo route at the time-minimizing levels, to ensure equilibrium.
\begin{align*}
  U_{BF}   &= -45w + \frac{tx}{6000} 
    &\text{(time disutility plus rebate)}\\
  U_{MoPo} &= -(20 + \frac{x}{100})w - t + \frac{tx}{6000}
    &\text{(time disutility minus tax plus rebate)}\\
  \Rightarrow -45w + \frac{tx}{6000} &= -20w - \frac{wx}{100} - t + \frac{tx}{6000}\\
  \Rightarrow t &= (25 - \frac{x}{100})w\\
    &= 12.5w &\text{(substitute $x = 1250$)}
\end{align*}
    * At this level, the tax will generate $tx = 12.5x \times 1250 = \$15,625w$ of revenue.
    * Relative to the no-toll equilibrium, the BF drivers are $+\frac{tx}{6000} = \$2.6w$ better off; because the system is at equilibrium, the MoPo drivers are better off by the same amount relative to the no-toll equilibrium.  We can also consider that the utility loss due to the tax on the MoPo drivers exactly cancels the utility gain of the reduced commute time; therefore, the net utility gain is just the rebate term.

### 8.2 Suppose that a monopolist controls the road through Middle Potato and sets the toll that maximizes total revenue. 

What price will the monopolist set and how many people will use the road at this price? How does this price compare with the optimal toll?

> __Hint__: _First find the "demand curve” relating number of users to price. Then find the revenue-maximizing quantity and price._

* Demand for access to the MoPo route is based on the price of the toll; demand will be at equilibrium when utility for commuter $i$ are equal: $U_{i,BF} = U_{i,MoPo}$.

\begin{align*}
  U_{BF}   &= -45w 
    &\text{(time disutility only)}\\
  U_{MoPo} &= -(20 + \frac{x}{100})w - t
    &\text{(time disutility minus toll)}\\
  \Rightarrow t &= (25 - \frac{x}{100})w &\text{(same as 8.1c)}\\
  \Rightarrow x &= 2500 - 100\frac{t}{w}
\end{align*}
    * Total revenue is then $R = xt = 2500t - \frac{100}{w}t^2$. 

\begin{align*}
  \frac{\dd R}{\dd t} &= 2500 - \frac{200}{w}t = 0\\
  \Rightarrow t &= 12.5w
\end{align*}
    * Therefore, marginal revenue = 0 when $t = 12.5w$, and $x = 1250$ commuters on the MoPo route.  Profit to the monopolist = $\$15,625w$.
    * Note this is also the point where price elasticity of demand is equal to 1, therefore maximizing revenue; for $dx = +1$, $dt/dx = -1/100w$:
$$e_p = -\frac{dx/x}{dt/t} = -\frac{1/1250}{-\frac{w}{100}/12.50w} = 1$$
* This is identical to the toll and number of MoPo commuters in the tax situation (8.1c).  A monopolist charging a profit-maximizing toll will reduce the traffic on the EPo/WePo commute system to minimize the total driving time across all commuters just as effectively as an optimal tax by the government (rebated or otherwise).


### 8.3 Suppose that the road through Middle Potato can be widened at a cost of $\$p$ per inch per day. 

If the road is widened by $H$ inches and if $N_1$ people use the road, the time that it would take to drive to from East Potato to West Potato by this road would be $20 + N_1/(100 + H)$. Suppose that the government's objective function is to maximize the total value of time saved from commuting minus the sum of money spent on road building. Let $w$ is the value per minute of time saved from commuting. Assuming that the government can not charge a toll for the road, or what values of the parameters $p$ and $w$ would it pay to widen the road at all. (Assume that there is no congestion for commuters coming home from work, only going to work.) If it pays to widen the road, how many commuters will be using the road when it is optimally widened? How long will it take them to make the trip, given that the road is optimally widened?

### 8.4 Suppose that as in the previous problem, the road through Middle Potato can be widened at a cost of $\$p$ per inch per day. 

Suppose also that the government can charge an efficient toll for using this road. What is the best combination of toll and highway expenditures? How does total toll revenue compare with the cost of building the highway? How does the optimal amount of highway expenditures compare with the optimal amount if the government cannot charge a toll? _Hint: Think about two possible corner solutions._

### 8.5 Generalize the bottleneck problem so that the cost per minute of being late can take a different value $\gamma$ from the cost per minute of being early. 
Show what happens in the limit as $\gamma$ gets large.

### 8.6 Generalize the bottleneck problem so that the everyone has a utility $u(t)$ for arriving at work at time $t$ where $u(t)$ is a fairly arbitrary singlepeaked (or single-plateaued) function.

(Assume that $u'(t) > -s\alpha$ for all relevant $t$.) Which results from our earlier discussion still apply and which do not?

### 8.7 What happens in the above generalization if $u'(t) < -s\alpha$?

### 8.8 Generalize the model to allow two types of commuters with different preferred times of arrival.

* Let type $x$ be those who prefer an early arrival time, and type $y$ be those who prefer a later arrival time.  Let $t_y^* = t_x^* + \tau$ where $\tau > 0$.  Let $N = N_x + N_y$.  Let the traffic wait time cost $\alpha$ be identical for all people, and office arrival penalty $\beta$ be identical for all people and identical for early and late arrivals.
* First note two degenerate cases; the first is when $\tau = 0$ which devolves to the basic case, and the second is when $\tau$ is very large, such that congestion from the two subpopulations do not overlap.  These cases are both boring, so ignore them.
* Assume that despite the different types, the equilibrium situation will result in all commuters having an equal average (dis)utility of commuting.
* Note that the very first commuter, leaving at time $t_1$, must be a type $x$ (a type $y$ would suffer a greater penalty for arriving that much earlier), and the last commuter, leaving at time $t_N$, must be a type $y$ (a type $x$ would similarly suffer a greater penalty for arriving that much later).  Neither of these will face a queue, so travel time is zero and cost is just arrival time penalty.
* Note that as long as there is a queue $D(t) > 0$ in the bottleneck at all times between $t_1$ and $t_N$, the total traffic jam will last $N/s$ as in the basic problem.  Commuter type is irrelevant in the flow rate through the bottleneck.
\begin{align*}
  t_N - t_1 &= \frac{N}{s}\\
  C_1 &= \beta (t_x^* - t_1) 
      &\text{(cost; first commuter is $x$)}\\
  C_N &= \beta (t_N - t_y^*) 
      &\text{(cost; last commuter is $y$)}\\
  C_1 = C_N &\Rightarrow \beta (t_x^* - t_1) = \beta (t_N - t_y^*)
      &\text{(equal costs)}\\
  \Rightarrow \beta (t_x^* - t_1) &= \beta (t_1 + \frac{N}{s} - (t_x^* + \tau))
      &\text{(sub for $t_y^*$ and $t_N$)}\\
  \Rightarrow t_x^* - t_1 &= \frac{N/s - \tau}{2}\\
  \Rightarrow t_N - t_y^* &= \frac{N/s - \tau}{2}
\end{align*}
* In the basic case, $t^* - t_1 = \frac{N}{2s}$.  In this case, assuming some $y$ commuters take pressure off the earliest commute, it seems OK that the time to leave becomes closer to $t_x^*$, but it seems like there should be some weighting by the number of $x$ and $y$ commuters.  For example, imagine 1000 type $x$ commuters; the first commuter leaves at $t_1 = t_x^* - 1000/2s$.  Then add a single type $y$, with $\tau = 1$ hour later.  This formulation says the first commuter should now leave at $t_1 = t_x^* - 1001/2s + \tau/2$, a half an hour later, just because of a single entrant who prefers a later time.  This seems to indicate one of the assumptions is faulty.


-----

## Exercises Lecture 9 

### 9.1 A city has 2 types of people, and 1000 people of each type. There is one private good and one public good. 

Let $X_i$ denote the amount of private consumption consumed by citizen $i$ and let $Y$ denote the amount of public good available in the city. All type 1s have the utility function
$U(X_i, Y) = X_iY$, type 2’s have the utility function $U(X_i, Y) = X_iY^2$. The price of private goods is \$1 per unit. Type 1s have an income of \$10,000 and Type 2s have an income of \$15,000. Public goods can be made from private goods with constant returns to scale. It takes 30 units of the private good to make one unit of the public good. The following questions relate to alternative arrangements for provision of public goods in this city.

a) Calculate the Lindahl equilibrium prices and quantities for this city.

b) Suppose that the public good is excludable and marketed competitively as in the Oakland (1974) model. In the Oakland competitive equilibrium with free entry for firms, how many units will be consumed by the type 1s? the type 2s? What will be the total number of units produced? What will the competitive prices be? How many units of the public good will the low price seller sell? How much will the high price seller sell.
