---
title: | 
  | \hfill \large{Casey O'Hara}
author: |
  | \hfill Econ 230B
date: |
  | \hfill `r Sys.Date()`
output:
  pdf_document:
    toc: no
    number_sections: false
  html_document:
    toc: no
    number_sections: false
    self_contained: no
#header-includes: 
#  - \usepackage{tikz}
#  - \usepackage{tikz-qtree}
#  - \usepackage{pgfplots}
#  - \usepackage{amsmath}
#  - \usepackage{mathrsfs}
#  - \usepackage{nccmath} 
---

``` {r setup, echo = FALSE, message = FALSE, warning = FALSE, include = FALSE}

knitr::opts_chunk$set(fig.width = 6, fig.height = 4, fig.path = 'figs/',
                      echo = FALSE, message = FALSE, warning = FALSE)

source('https://raw.githubusercontent.com/oharac/src/master/R/common.R')
### loads tidyverse packages, defines helper functions

library(tidyverse)
library(latex2exp)

```

\newcommand{\EE}{\mathbb{E}}
\newcommand{\eps}{\varepsilon}
\newcommand{\LL}{\mathscr{L}}
\newcommand{\dd}{\partial}

# Problem set 6

## Exercises lecture 10

### 10.1 Explain why it is that in the pivotal mechanism, it is a weakly dominant strategy to tell the truth.  Write your explanation in such a way that it is convincing for an intelligent person who has not studied game theory.

Assume you are voting on a simple yes/no proposal.  Your vote is weighted by your stated strength of preference of an outcome (e.g. your name and a dollar bid put into the "yes" jar), so if you are very interested in a "yes" outcome, you could bid a higher dollar value you'd be willing to pay to see that outcome happen.  The final outcome is determined by the difference in value offered by all "no" voters vs. the dollars offered by all "yes" voters.  For example, if there are \$100 put in the "yes" jar and \$99 put in the "no" jar, the proposition passes by a margin of +\$1 (+ for "yes" votes, - for "no").

Your vote is pivotal if it changes the outcome; i.e. if your (dollar-weighted) vote were removed, the decision of the vote would flip.  In the above case, if you bid \$2 or higher for "yes", your vote is pivotal (Pivotal status of a \$1 "yes" bid is probably subject to a decision rule about tie votes), and the same would be true for _any_ voter bidding \$2 or more for "yes".  Note a vote for "no" is not pivotal in this case - removing that vote would not change the outcome.

The pivotal mechanism works by taxing pivotal voters by the margin that would have occurred if they alone hadn't voted.  In the above situation, if you bid \$5 for "yes", your vote would be pivotal - if you didn't vote, the outcome would have been 99 "no" and 95 "yes" - a difference of -\$4 - so you'd be taxed that difference of \$4, which would be collected and kept by the voting authority.

So why does this make truth a weakly dominant strategy?  If you truly valued the "yes" outcome at \$5, then you gain \$5 of satisfaction from the outcome, and give up only \$4, for a total satisfaction of \$1.  If you tried to game the system by overstating your value, say \$6, you would pay a tax of \$5 and end up with a total satisfaction of \$0 (your true benefit from "yes" minus your tax), so you are worse off than had you told the truth.  If your vote is pivotal, a truth strategy will result in a better outcome than overbidding; in the event that your vote is not pivotal, overbidding will not make you any better or worse off than the truth.   Thus the truth is weakly dominant over an overbidding strategy.

Similarly for underbidding - if in the above case, you decide to bid below your valuation, say \$2, then the final tally would have been 99 "no" and 97 "yes" - and you would miss out on your \$5 valuation of the "yes" outcome, so you are worse off than had you told the truth - thus truth is again dominant.  Note again, if your truthful vote would have not been pivotal, your underbid just leaves you equally well off as the truth - no gain or loss for the underbid, therefore once again, truth is weakly dominant over an underbidding strategy.

### 10.2 Prove the assertion in the text that a Pareto improvement could be achieved by passing the ban and making appropriate side-payments if $\sum V_i > 0$, and could not be achieved if $\sum V_i < 0$.

As in the text, let $i$'s willingness to pay for the ban be quantity of private goods $V_i$ such that
$$U_i(X_i - V_i, 1) = U_i(X_i, 0) \hspace{6pt}\forall i$$
where $V_i > 0$ for those that favor the ban, and $V_i < 0$ for those that oppose it.  

<!--If $X_i$ and $V_i$ are in money and money is numeraire, then
$$U_i(X_i, 1) - V_i = U_i(X_i, 0) \hspace{6pt}\forall i$$
-->
The total population is $N$; let there be $F$ people in favor of the Ban, and $A = N - F$ against (without loss of generalization, let them be ordered from most in favor to most opposed).

If those in favor can, in aggregate, scrape together more than enough to cover the costs to those opposed while maintaining a small surplus on their side, they can pay off those opposed to the point of indifference, with a few paid off above the point of indifference to change their vote.  Those in favor each chip in a side payment $p_{i,F} = V_i - r_F$, where $r_F$ is an arbitrarily small residual to keep them in favor rather than being just indifferent to the ban.
$$U_i^F(X_i - p_{i,F}, 1) = U_i^F(X_i - V_i + r_F, 1) > U_i^F(X_i - V_i, 1) = U_i^F(X_i, 0)$$
So all those for the ban are still better off if the ban passes than if it does not.

If these side payments are aggregated and used to buy off those against by paying their WTP plus a small residual, i.e. $p_{i,A} = -V_i + r_A$ (negative $V_i$ because to these people, $V_i < 0$):
$$U_i^A(X_i + p_{i,A}, 1) = U_i^A(X_i - V_i + r_A, 1) > U_i^A(X_i - V_i, 1) = U_i^A(X_i, 0)$$
So in the event of the ban, those against would be marginally better off than in the no-ban case.  So assuming these side payments exist, then the sum of the payments from those in favor can pay off the sum of costs of those against.  The ban occurs, and those in favor get the benefit of the ban while those opposed are no worse off - i.e., Pareto improvement.

To prove it, assume the side payments described above exist; also let $r_A$ and $r_F$ such that $\delta = \sum_{i=F+1}^N r_A - \sum_{i=1}^F r_F > 0$
:
\begin{align*}
  \exists \vec{p}_F \text{ and } \vec{p}_A \text{ such that }\sum_{i=1}^F p_{i,F} &> \sum_{i=F+1}^N p_{i,A}\\
  \Leftrightarrow \sum_{i=1}^F V_i + \sum_{i=1}^F r_F &> \sum_{i=F+1}^N (-V_i) + \sum_{i=F+1}^N r_A\\
  \Leftrightarrow \sum_{i=1}^F V_i &> \sum_{i=F+1}^N (-V_i) + \delta\\
  \Leftrightarrow \sum_{i=1}^F V_i &- \sum_{i=F+1}^N (-V_i) > \delta\\
  \Leftrightarrow \sum_{i=1}^F V_i &+ \sum_{i=F+1}^N V_i > \delta\\
  \Leftrightarrow \sum_{i=1}^N V_i &> \delta
\end{align*}

Since $r_A$ and $r_F$ are arbitrarily small, $\delta > 0$ can be arbitrarily small.  Therefore, if side payments exist that create Pareto improvement, it follows that $\sum_{i=1}^N V_i > \delta > 0$, and if $\sum_{i=1}^N V_i > \delta > 0$ then side payments exist.

On the other hand, if those opposed to the ban can pay off those in favor to make them indifferent to the lack of ban, then the inequalities reverse and $\sum_{i=1}^N V_i < 0$.  The ban does not pass, and those who opposed it avoid the costs of the ban while those who wanted the ban are no worse off, therefore Pareto improvement occurs in that case as well.
