---
title: | 
  | \hfill \Large{Math Camp: PS 3 Probability and Statistics}
author: |
  | \hfill Casey O'Hara
date: |
  | \hfill `r Sys.Date()`
output:
  pdf_document:
    toc: no
  html_document:
    toc: no
---

\begin{enumerate} 
\item
  \textbf{Let $Y$ be a continuous random variable with PDF}
  \begin{align*}
    f_Y(y) = \begin{cases}
               (3/2)y^2 + y &\text{if $0\leq y \leq 1$}\\
               0            &\text{else}
            \end{cases}
  \end{align*}
  \begin{enumerate}
    \item Find the mean of $Y$.\\
      Mean = $\mathbb{E}[Y]$
      \begin{align*}
        \mathbb{E}[Y] &= \int_{-\infty}^{\infty} y f(y) dy\\
        &= \int_{0}^{1} y((3/2)y^2 + y) dy 
          + 0 \biggr\rvert_{-\infty}^0 + 0 \biggr\rvert_{1}^{\infty}\\
        &=  \left(\frac{1}{4}*\frac{3}{2}y^4 + \frac{1}{3}y^3\right)\biggr\rvert_0^1\\
        &= \frac{3}{8} + \frac{1}{3} = \frac{17}{24}
      \end{align*}
    \item Find the variance of $Y$.
      Variance = $\mathbb{E}[Y^2] - \mathbb{E}[Y]^2$
      \begin{align*}
        \mathbb{E}[Y^2] &= \int_{-\infty}^{\infty} y^2 f(y) dy\\
        &= \int_{0}^{1} y^2((3/2)y^2 + y) dy 
          + 0 \biggr\rvert_{-\infty}^0 + 0 \biggr\rvert_{1}^{\infty}\\
        &=  \left(\frac{1}{5}*\frac{3}{2}y^5 + \frac{1}{4}y^4\right)\biggr\rvert_0^1\\
        &= \frac{3}{10} + \frac{1}{4} = \frac{11}{20}\\
        var(Y) &= \mathbb{E}[Y^2] - \mathbb{E}[Y]^2\\
        & = \frac{11}{20} - \left(\frac{17}{24}\right)^2\\
        &= 0.0483
      \end{align*}
  \end{enumerate}
  
  \item
  \textbf{Let $Y$ be a random variable with probability density function given by}
  \begin{align*}
    f_Y(y) = 2(1-y), \hspace{20pt} y \in [0, 1]
  \end{align*}
  \begin{enumerate}
    \item Find the PDF of $U = 2Y - 1$.\\
      $U$ is a strictly increasing function, so using transformation method.
      \begin{align*}
        U &= 2Y - 1 \Rightarrow Y = \frac{u+1}{2}\\
        f_U(u) &= f_y\left(\frac{u+1}{2}\right) \left| \frac{d}{du}\left(\frac{u+1}{2}\right) \right| \\
        &= 2 \left( 1 - \frac{u+1}{2} \right) \left| \frac{1}{2} \right|\\
        f_U(u) &= \frac{1-u}{2}, \hspace{20pt} u \in[-1, 1]
      \end{align*}
      
    \item Find the PDF of $W = 1 - 2Y$.\\
      $W$ is a strictly decreasing function, so using transformation method.
      \begin{align*}
        W &= 1 - 2Y \Rightarrow Y = \frac{1 - w}{2}\\
        f_W(w) &= f_y\left(\frac{1-w}{2}\right) \left| \frac{d}{dw}\left(\frac{1-w}{2}\right) \right| \\
        &= 2 \left( 1 - \frac{1-w}{2} \right) \left| -\frac{1}{2} \right|\\
        f_W(w) &= \frac{1+w}{2}, \hspace{20pt} w \in[-1, 1]
      \end{align*}
      
    \item Find the PDF of $Z = Y^2$.\\
      $Z$ is neither a strictly increasing nor decreasing function for all 
      values of Y, though across the support of $Y \in [0, 1]$, it is 
      strictly increasing; so using transformation method.
      \begin{align*}
        Z &= Y^2 \Rightarrow Y = \sqrt{Z}\\
        f_Z(z) &= f_y(\sqrt{z}) \left| \frac{d}{dz}\sqrt{z} \right| \\
        &= 2 ( 1 - \sqrt{z} ) \left| \frac{1}{2}z^{-1/2} \right|\\
        f_Z(z) &= \frac{\sqrt{z}}{z} - 1, \hspace{20pt} z \in[0, 1]
      \end{align*}
  \end{enumerate}
  
\item Consider the multivariate distribution characterized by the PDF
  \begin{align*}
    f_{XY} = 6(1-y), \hspace{20pt} 0 \leq x \leq y \leq 1
  \end{align*}
  \begin{enumerate}
    \item Find the conditional expectation of $\mathbb{E}[X|Y = y]$.\\
      \begin{align*}
        \mathbb{E}[X|Y = y] &= \frac{f_{XY}(x, y)}{f_Y(y)} = \frac{\text{joint PDF}}{\text{marginal PDF}}\\
        f_Y(y) &= \int_0^y 6(1-y)dx\\
               &= 6y(1 - y)\\[10pt]
        \mathbb{E}[X|Y = y] &= \frac{f_{XY}(x, y)}{f_Y(y)}\\
        &= \frac{6(1-y)}{6y(1-y)}\\
        &= \frac{1}{y}
      \end{align*}
      
    \item Find the covariance of $X$ and $Y$.\\
      \begin{align*}
        cov(X, Y) &= \mathbb{E}[XY] - \mathbb{E}[X]\mathbb{E}[Y]\\[10pt]
        \mathbb{E}[XY] &= \int_{y=0}^1\int_{x=0}^y xy*6(1-y)dx dy\\
          &= \int_{y=0}^1 \left( \frac{1}{2}*6x^2(y-y^2) \right) \biggr\rvert_0^y dy\\
          &= \int_{y=0}^1 (3y^3 - 3y^4)) dy\\
          &= \frac{3}{4}y^4 - \frac{3}{5}y^5 \biggr\rvert_0^1\\
          &= \frac{3}{20}\\[15pt]
        \mathbb{E}[X] &= \int_0^1 x*f_X(x) dx\\
          f_X(x) &= \int_x^1 f_{XY}(x, y) dy = 6y - 3y^2 \biggr\rvert_x^1\\
          \mathbb{E}[X] &= \int_0^1 x(3 - 6x + 3x^2) dx\\
            &= \frac{3}{2}x^2 - \frac{1}{3} * 6x^3 + \frac{1}{4} * 3x^4 \biggr\rvert_0^1\\
            &= \frac{3}{2} - \frac{1}{3} + \frac{3}{4} = \frac{3}{12} = \frac{1}{4}\\[15pt]
        \mathbb{E}[Y] &= \int_0^1 y*f_Y(y) dy\\
          f_Y(y) &= \int_0^y f_{XY}(x, y) dx = 6x - 6xy \biggr\rvert_0^y\\
          \mathbb{E}[Y] &= \int_0^1 y(6y - 6y^2) dy\\
            &= \frac{6}{3}y^3 - \frac{6}{4}y^4 \biggr\rvert_0^1\\
            &= 2 - \frac{3}{2} = \frac{1}{2}\\[15pt]
        cov(X, Y) &= \mathbb{E}[XY] - \mathbb{E}[X]\mathbb{E}[Y]\\
          &= \frac{3}{20} - \frac{1}{4}*\frac{1}{2} = \frac{1}{40}
      \end{align*}
  \end{enumerate}
  
\item
  \textbf{Let $X_1, ..., X_n$ be a random variable from a distribution with PMF}
  \begin{align*}
    f(x_i|\theta) = \begin{cases}
               \theta(1-\theta)^{x_i - 1} &\text{if $x = 1, 2, 3...$}\\
               0            &\text{else}
            \end{cases}
  \end{align*}
  where $\theta \in (0, 1)$.
  \begin{enumerate}
    \item Find the method of moments estimator for $\theta$.\\
    \begin{align*}
      m_1 &= M_1(\hat\theta)\\
      M_1(\hat\theta) = \mathbb{E}[X] &= \sum_{i=1}^\infty x_i \theta(1 - \theta)^{x_i - 1}\\
      &= \theta[1 + 2(1-\theta) + 3(1-\theta)^2 + 4(1 - \theta)^3 ...]\\
      &\text{similar to geometric series but not quite...}\\
      \mathbb{E}[X] - (1 - \theta)\mathbb{E}[X] &=  
        \theta[1 + 2(1-\theta) + 3(1-\theta)^2 + 4(1 - \theta)^3...]\\
        & \hspace{20pt} - \theta[(1-\theta) + 2(1-\theta)^2 + 3(1 - \theta)^3...]\\
        &= \theta[1 + (1-\theta) + (1-\theta)^2 + (1-\theta)^3 ...]\\
      &\text{Now it's a geom series; $\sum ar^x \rightarrow \frac{1}{1-r}$...}\\
      \mathbb{E}[X] - (1 - \theta)\mathbb{E}[X] &= \theta(\frac{1}{1 - (1 - \theta)}) = 1\\
      m_1 &= \mathbb{E}[X] = \frac{1}{\theta}
    \end{align*}

  \end{enumerate}
      
\end{enumerate}

